// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN1Q5lCKXlDjRo7uJkSYTa01D5TuaeGh4',
    appId: '1:375599021687:web:a736c57295373618339072',
    messagingSenderId: '375599021687',
    projectId: 'ecommerce-7c899',
    authDomain: 'ecommerce-7c899.firebaseapp.com',
    storageBucket: 'ecommerce-7c899.appspot.com',
    measurementId: 'G-8S94MBF4FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Gn8LduEsFsJkhv4M4PT7prWBvBwlHPc',
    appId: '1:375599021687:android:5922e4db2d2dcdbe339072',
    messagingSenderId: '375599021687',
    projectId: 'ecommerce-7c899',
    storageBucket: 'ecommerce-7c899.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuYoeKz7ywUxYT0idK_ZxohNpf2x9Kuxk',
    appId: '1:375599021687:ios:f34b57d88acd32a4339072',
    messagingSenderId: '375599021687',
    projectId: 'ecommerce-7c899',
    storageBucket: 'ecommerce-7c899.appspot.com',
    iosClientId: '375599021687-gi0dpt5qpdgab2aho3bfdh93634arfp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceMuzamil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuYoeKz7ywUxYT0idK_ZxohNpf2x9Kuxk',
    appId: '1:375599021687:ios:f34b57d88acd32a4339072',
    messagingSenderId: '375599021687',
    projectId: 'ecommerce-7c899',
    storageBucket: 'ecommerce-7c899.appspot.com',
    iosClientId: '375599021687-gi0dpt5qpdgab2aho3bfdh93634arfp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceMuzamil',
  );
}
